name: quantum_terminal
description: A quantum-themed terminal interface portfolio built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono.ttf
      
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode.ttf
     
          
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro.ttf
       
          
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBMPlexMono.ttf
        

